export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_RANK_MENU = 'SET_RANK_MENU';

export const SET_POP_MENU = 'SET_POP_MENU';

export const SET_RISING_MENU = 'SET_RISING_MENU';

export const SET_CATEGORY_ITEM_LIST = 'SET_CATEGORY_ITEM_LIST';