export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_RANK_MENU = 'SET_RANK_MENU';

export const SET_POP_MENU = 'SET_POP_MENU';

export const SET_RISING_MENU = 'SET_RISING_MENU';

export const SET_CATEGORY_ITEM_LIST = 'SET_CATEGORY_ITEM_LIST';

export const SET_CATEGORY_ITEM_TITLE = 'SET_CATEGORY_ITEM_TITLE';

export const SET_MENU_DETAIL = 'SET_MENU_DETAIL';

export const SET_RANK_DETAIL = 'SET_RANK_DETAIL';

export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
